---
- name: Remove conflicting packages
  ansible.builtin.apt:
    name: "{{ docker_conflict_packages }}"
    state: absent

- name: Install required packages for Docker
  ansible.builtin.apt:
    name: "{{ docker_required_packages }}"
    state: present
    update_cache: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    update_cache: true

- name: Install Docker with dependecies
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
